POST http://localhost:8080/posts
Content-Type: application/json

{
  "coordinates": "37.5665, 126.9780",
  "name": "Lanai Purple Church cross",
  "location": "해외",
  "type": "F"
}

### 국내
### 해외

POST https://translation.sample-api.com/translation
Content-Type: application/json
Authorization: Bearer Carpenstreet-Backend-Engineer
X-Language: en

{
  "text": "테스트 문장"
}