spring:
  application:
    name: pickmin-bloom
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/pickmin-bloom?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    username: admin
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
datasource:
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password:
  driver-class-name: org.h2.Driver
  platform: h2

#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        # show_sql: true
#        #        format_sql: true
#        #        use_sql_comments: true
#        dialect: org.hibernate.dialect.MySQLDialect
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      show_sql: true
      format_sql: true
      use_sql_comments: true
