version: 0.2.1
spring:
  application:
    name: pickmin-bloom
  datasource:
    url: jdbc:mysql://pickmin-bloom.c18ys0iw669m.ap-northeast-2.rds.amazonaws.com/pickmin_bloom?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ec2
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: false
        highlight_sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_KEY}
            client-secret: ${GOOGLE_OAUTH_SECRET_KEY}
            redirect-uri: "https://pickmin-map.com/login/oauth2/code/google"
#            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - profile
              - email
  thymeleaf:
    prefix: classpath:/templates/         # Thymeleaf 템플릿 폴더 위치
    suffix: .html                         # Thymeleaf 템플릿 파일 확장자
    mode: HTML5                           # Thymeleaf 처리 모드
    encoding: UTF-8                       # 파일 인코딩 설정
    cache: false                          # 캐싱 비활성화 (개발 시 편리)
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  hikari:
    minimum-idle: 5                     # 유휴 상태로 유지할 최소 커넥션 수
    maximum-pool-size: 10               # 최대 커넥션 수 (RDS 제한 고려!)
    idle-timeout: 600000                # 커넥션 유휴 상태 유지 시간 (ms)
    max-lifetime: 1800000               # 커넥션 생존 최대 시간 (ms)
    connection-timeout: 30000           # 커넥션 획득 시도 타임아웃 (ms)
    pool-name: HikariPool-Pickmin-Bloom # 로깅 시 보이는 풀 이름

logging:
  level:
    com.zaxxer.hikari: INFO  # HikariCP 로그 레벨 (커넥션 풀 상태 확인용)
    root: INFO
    org.hibernate.SQL: OFF  # Hibernate가 실행하는 SQL 로그 출력 비활성화 (보안/성능 이유)
    org.hibernate.type.descriptor.sql.BasicBinder: OFF  # SQL 파라미터 바인딩 로그 비활성화 (민감정보 노출 우려)
    org.hibernate.orm.jdbc.bind: OFF  # JDBC 바인딩 상세 로그 비활성화 (TRACE 수준은 운영에 불필요)
    org.hibernate.orm.jdbc.extract: OFF  # JDBC 결과 추출 로그 비활성화 (불필요한 디스크 사용 방지)

aws:
  s3:
    publicBaseUrl: https://pickmin-post.s3.ap-northeast-2.amazonaws.com
    region: ap-northeast-2
    bucket:
      post: pickmin-post
    presigned:
      duration: 300
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
server:
  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 1d
      tracking-modes: cookie
      cookie:
        secure: true
        same-site: None
  tomcat:
    threads:
      max: 100
      min-spare: 10

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

  endpoint:
    health:
      show-details: always

  metrics:
    enable:
      all: true                  # 모든 메트릭 수집 활성화