version: 0.0.0
spring:
  application:
    name: pickmin-bloom
  datasource:
    url: jdbc:mysql://pickmin-bloom.c18ys0iw669m.ap-northeast-2.rds.amazonaws.com/pickmin_bloom?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: padmin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        highlight_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_KEY}
            client-secret: ${GOOGLE_OAUTH_SECRET_KEY}
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - profile
              - email
  thymeleaf:
    prefix: classpath:/templates/         # Thymeleaf 템플릿 폴더 위치
    suffix: .html                         # Thymeleaf 템플릿 파일 확장자
    mode: HTML5                           # Thymeleaf 처리 모드
    encoding: UTF-8                       # 파일 인코딩 설정
    cache: false                          # 캐싱 비활성화 (개발 시 편리)
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
            extract: TRACE
aws:
  s3:
    publicBaseUrl: https://pickmin-bloom-post.s3.ap-northeast-2.amazonaws.com
    region: ap-northeast-2
    bucket:
      post: pickmin-bloom-post
    presigned:
      duration: 300
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
server:
  servlet:
    session:
      timeout: 1d